import type { Phase } from "@/lib/content/types";

const defaultScore = { excellent: 3 as const, adequate: 2 as const, inadequate: 0 as const };

export const chapter1Phases: Phase[] = [
  {
    id: "chapter-1-phase-1",
    chapterId: "chapter-1",
    number: 1,
    title: "O Primeiro Sopro",
    coreConcept: "Tetravalência do carbono e formação da primeira molécula estável.",
    technicalType: "construction",
    displayType: "Construção",
    narrative: "No início da jornada, o jogador recebe seu primeiro átomo de carbono e precisa compreender a regra fundamental do reino: o carbono só alcança estabilidade quando completa corretamente suas ligações.",
    objective: "Construir a primeira molécula estável do jogo.",
    resources: { carbonAvailable: 1, hydrogenMode: "implicit_infinite", availableFragments: ["ligacao_simples"], supportCards: ["carbono", "hidrogenio", "ligacao_simples"] },
    availableMolecules: ["metano"],
    excellentAnswer: "metano",
    adequateAnswers: [],
    expectedProperties: ["saturada", "aberta", "homogenea", "normal", "baixa_polaridade", "alta_volatilidade"],
    pedagogicalNotes: [
      "massa e entalpia de combustão podem aparecer como informação de apoio na carta, mas não entram como justificativa principal clicável nesta fase",
      "o foco principal da fase é a ideia de estabilidade estrutural do carbono",
      "esta fase funciona como introdução ao fluxo de construção e validação",
    ],
    rewards: { carbon: 1, unlockedMolecule: "metano", unlockedTitle: "Centelha de Carbono" },
    feedback: {
      excellent: "Você criou o Metano, o Primeiro Sopro. A estrutura está estável e respeita corretamente as ligações do carbono.",
      inadequate: "Não foi possível criar a molécula. Verifique se as ligações estão consistentes e tente novamente.",
    },
    score: defaultScore,
  },
  {
    id: "chapter-1-phase-2",
    chapterId: "chapter-1",
    number: 2,
    title: "A Ponte das Cadeias",
    coreConcept: "Ligação entre carbonos e crescimento da cadeia carbônica.",
    technicalType: "construction",
    displayType: "Construção",
    narrative: "Depois de dominar a primeira molécula, o jogador aprende que carbonos podem se unir entre si, formando cadeias maiores e abrindo novas possibilidades estruturais.",
    objective: "Construir uma molécula estável com dois carbonos ligados por ligação simples.",
    resources: { carbonAvailable: 2, hydrogenMode: "implicit_infinite", availableFragments: ["ligacao_simples"], supportCards: [] },
    availableMolecules: ["metano", "etano"],
    excellentAnswer: "etano",
    adequateAnswers: [],
    expectedProperties: ["saturada", "aberta", "homogenea", "normal", "baixa_polaridade", "alta_volatilidade"],
    pedagogicalNotes: [
      "massa e entalpia de combustão seguem como informações de apoio na carta, não como justificativa principal clicável",
      "a fase deve reforçar que a ligação C-C substitui ligações com hidrogênio",
      "esta fase consolida a diferença entre somar átomos e formar uma estrutura válida",
    ],
    rewards: { carbon: 1, unlockedMolecule: "etano", unlockedTitle: "Guardião do Metano" },
    feedback: {
      excellent: "Você construiu o Etano corretamente. A cadeia cresceu e os carbonos continuam respeitando suas quatro ligações.",
      inadequate: "A estrutura ainda não está válida. Quando os carbonos se ligam entre si, cada um continua precisando completar corretamente suas ligações.",
    },
    score: defaultScore,
  },
  {
    id: "chapter-1-phase-3",
    chapterId: "chapter-1",
    number: 3,
    title: "A Tocha do Portão Norte",
    coreConcept: "Hidrocarbonetos como combustíveis e comparação entre alcanos pequenos.",
    technicalType: "choice",
    displayType: "Escolha",
    narrative: "Diante de uma tocha ancestral, o jogador precisa identificar qual das cadeias disponíveis melhor sustenta a chama e representa o uso energético dos hidrocarbonetos.",
    objective: "Construir e escolher a molécula mais adequada para alimentar a Tocha do Portão Norte.",
    resources: { carbonAvailable: 3, hydrogenMode: "implicit_infinite", availableFragments: ["ligacao_simples"], supportCards: [] },
    availableMolecules: ["metano", "etano", "propano"],
    excellentAnswer: "propano",
    adequateAnswers: ["metano", "etano"],
    expectedProperties: ["saturada", "aberta", "homogenea", "normal", "baixa_polaridade", "util_como_combustivel", "alto_potencial_energetico"],
    pedagogicalNotes: [
      "massa e entalpia de combustão podem aparecer como apoio de leitura na carta",
      "o propano é a resposta ideal por representar melhor o contexto do desafio",
      "metano e etano continuam corretos como combustíveis, mas menos representativos para esta fase",
      "o aluno só desbloqueia a carta do propano se efetivamente construir propano na oficina",
    ],
    rewards: { carbon: 1, unlockedMolecule: "propano", unlockedTitle: "Forjador de Cadeias" },
    feedback: {
      excellent: "Excelente escolha. O Propano representa muito bem o uso energético dos hidrocarbonetos e sustenta a chama do desafio com grande eficiência.",
      adequate: "Boa escolha. Sua molécula também pode funcionar como combustível, mas existe uma opção ainda mais representativa para este contexto.",
      inadequate: "Essa molécula não é a melhor resposta para o desafio da tocha. Tente comparar melhor as cartas disponíveis e suas aplicações.",
    },
    score: defaultScore,
  },
  {
    id: "chapter-1-phase-4",
    chapterId: "chapter-1",
    number: 4,
    title: "O Véu dos Vapores",
    coreConcept: "Volatilidade e relação entre tamanho da cadeia e dispersão.",
    technicalType: "choice",
    displayType: "Escolha",
    narrative: "Em um vale coberto por névoa, o jogador precisa reconhecer qual molécula consegue se dispersar com mais facilidade e atravessar o ambiente com maior eficiência.",
    objective: "Escolher a molécula mais adequada para atravessar o Véu dos Vapores.",
    resources: { carbonAvailable: 3, hydrogenMode: "implicit_infinite", availableFragments: ["ligacao_simples"], supportCards: [] },
    availableMolecules: ["metano", "etano", "propano"],
    excellentAnswer: "metano",
    adequateAnswers: ["etano"],
    expectedProperties: ["cadeia_curta", "alta_volatilidade", "baixa_polaridade"],
    pedagogicalNotes: [
      "esta fase deve ser mais permissiva para manter a progressão confortável",
      "o metano é a resposta ideal por ser a menor molécula disponível",
      "o etano continua sendo aceitável, embora menos eficiente",
      "o propano é tratado como inadequado neste contexto",
      "a comparação entre tamanho da cadeia e volatilidade é o centro conceitual da fase",
    ],
    rewards: { fragments: ["ligacao_dupla"], unlockedTitle: "O Volátil" },
    feedback: {
      excellent: "Excelente escolha. O Metano é a molécula mais volátil entre as disponíveis e atravessa o véu com maior facilidade.",
      adequate: "Boa escolha. Sua molécula ainda apresenta volatilidade relevante, mas existe uma alternativa mais eficiente para este desafio.",
      inadequate: "Essa molécula não atravessa o Véu dos Vapores com a mesma eficiência. Compare melhor o tamanho da cadeia e a volatilidade das opções disponíveis.",
    },
    score: defaultScore,
  },
  {
    id: "chapter-1-phase-5",
    chapterId: "chapter-1",
    number: 5,
    title: "A Ruptura da Saturação",
    coreConcept: "Introdução à ligação dupla e diferença entre alcano e alceno.",
    technicalType: "construction",
    displayType: "Construção",
    narrative: "Ao avançar no reino, o jogador descobre que nem toda molécula precisa permanecer saturada. A ligação dupla surge como um novo recurso estrutural e introduz uma nova lógica de reatividade.",
    objective: "Construir uma molécula de dois carbonos mais reativa que o etano.",
    resources: { carbonAvailable: 4, hydrogenMode: "implicit_infinite", availableFragments: ["ligacao_simples", "ligacao_dupla"], supportCards: [] },
    availableMolecules: ["metano", "etano", "propano", "eteno"],
    excellentAnswer: "eteno",
    adequateAnswers: [],
    expectedProperties: ["insaturada", "aberta", "homogenea", "normal", "baixa_polaridade", "alta_reatividade"],
    pedagogicalNotes: [
      "esta fase marca a entrada oficial da ligação dupla como recurso de construção",
      "a principal aprendizagem é que a mudança no tipo de ligação altera a fórmula e o comportamento químico",
      "a carta do eteno deve deixar evidente a diferença entre saturação e insaturação",
    ],
    rewards: { carbon: 1, unlockedMolecule: "eteno", unlockedTitle: "Arauto da Insaturação" },
    feedback: {
      excellent: "Excelente construção. O Eteno introduz a insaturação e representa uma molécula mais reativa que o etano.",
      inadequate: "A estrutura construída ainda não representa corretamente uma molécula insaturada. Revise o uso da ligação dupla e tente novamente.",
    },
    score: defaultScore,
  },
  {
    id: "chapter-1-phase-6",
    chapterId: "chapter-1",
    number: 6,
    title: "A Porta da Transformação",
    coreConcept: "Aplicação da reatividade dos alcenos em contexto de transformação química.",
    technicalType: "construction_choice",
    displayType: "Construção + escolha",
    narrative: "Diante de uma porta selada por runas, o jogador precisa reconhecer que certas moléculas são valiosas não por sua estabilidade, mas por sua capacidade de reagir e originar novas estruturas.",
    objective: "Construir e escolher a molécula mais adequada para iniciar uma transformação química.",
    resources: { carbonAvailable: 4, hydrogenMode: "implicit_infinite", availableFragments: ["ligacao_simples", "ligacao_dupla"], supportCards: [] },
    availableMolecules: ["metano", "etano", "propano", "eteno", "propeno"],
    excellentAnswer: "eteno",
    adequateAnswers: ["propeno"],
    expectedProperties: ["insaturada", "aberta", "homogenea", "normal", "baixa_polaridade", "alta_reatividade", "util_como_precursor_de_transformacao"],
    pedagogicalNotes: [
      "tanto eteno quanto propeno são alcenos e resolvem o problema",
      "o eteno é mantido como resposta ideal por ser o exemplo mais direto e introdutório",
      "o propeno aparece como resposta correta aceitável",
      "a fase reforça que, em certos contextos, maior reatividade é mais importante do que estabilidade",
    ],
    rewards: { unlockedMolecule: "propeno", unlockedTitle: "Mestre da Ruptura" },
    feedback: {
      excellent: "Excelente escolha. O Eteno representa de forma direta a reatividade dos alcenos e responde muito bem ao desafio da transformação.",
      adequate: "Boa escolha. O Propeno também é adequado para transformação química, embora o Eteno seja a referência mais direta para esta fase.",
      inadequate: "Essa molécula não é a mais apropriada para iniciar transformações rápidas. Compare melhor a reatividade entre alcanos e alcenos.",
    },
    score: defaultScore,
  },
  {
    id: "chapter-1-phase-7",
    chapterId: "chapter-1",
    number: 7,
    title: "A Oficina dos Polímeros",
    coreConcept: "Uso de alcenos como precursores de polímeros.",
    technicalType: "choice",
    displayType: "Escolha",
    narrative: "Na Oficina dos Polímeros, o jogador encontra um novo problema: identificar qual molécula pode abrir caminho para a formação de longas cadeias materiais.",
    objective: "Escolher a molécula mais adequada para servir de precursor de um polímero.",
    resources: { carbonAvailable: 4, hydrogenMode: "implicit_infinite", availableFragments: ["ligacao_simples", "ligacao_dupla"], supportCards: [] },
    availableMolecules: ["metano", "etano", "propano", "eteno", "propeno", "buteno"],
    excellentAnswer: "eteno",
    adequateAnswers: ["propeno", "buteno"],
    expectedProperties: ["insaturada", "aberta", "homogenea", "normal", "alta_reatividade", "util_para_polimeros", "util_como_precursor_de_transformacao"],
    pedagogicalNotes: [
      "o eteno é a resposta ideal por seu papel clássico como monômero introdutório",
      "propeno e buteno também são aceitáveis no contexto geral de polimerização",
      "a fase deve reforçar a ligação entre insaturação e reações de adição",
    ],
    rewards: { carbon: 2, unlockedMolecule: "buteno", unlockedTitle: "Artesão das Cadeias Vivas" },
    feedback: {
      excellent: "Excelente escolha. O Eteno é a referência mais direta e clássica para introduzir a formação de polímeros por adição.",
      adequate: "Boa escolha. Sua molécula também pode participar de processos de polimerização, mas existe uma resposta mais direta para esta fase introdutória.",
      inadequate: "Essa molécula não é a mais apropriada para iniciar a formação de polímeros. Reavalie o papel das ligações duplas nesse processo.",
    },
    score: defaultScore,
  },
  {
    id: "chapter-1-phase-8",
    chapterId: "chapter-1",
    number: 8,
    title: "A Coroa Aromática",
    coreConcept: "Introdução à aromaticidade como forma especial de estabilidade.",
    technicalType: "construction_choice",
    displayType: "Construção + escolha",
    narrative: "No centro do reino, o jogador encontra uma estrutura diferente de tudo o que viu até agora: uma organização carbônica especial, estável e distinta das insaturações comuns.",
    objective: "Construir e escolher a molécula que representa estabilidade especial em uma estrutura carbônica avançada.",
    resources: { carbonAvailable: 6, hydrogenMode: "implicit_infinite", availableFragments: ["ligacao_simples", "ligacao_dupla", "estrutura_aromatica"], supportCards: [] },
    availableMolecules: ["metano", "etano", "propano", "eteno", "propeno", "buteno", "benzeno"],
    excellentAnswer: "benzeno",
    adequateAnswers: [],
    expectedProperties: ["aromatica", "fechada", "homogenea", "baixa_polaridade", "estabilidade_especial", "adequada_para_meio_apolar"],
    pedagogicalNotes: [
      "esta fase encerra o capítulo introduzindo a diferença entre alceno comum e sistema aromático",
      "não há resposta adequada equivalente ao benzeno nesta fase",
      "a ideia central não é apenas ter ligação dupla, mas reconhecer uma organização estrutural especial",
      "a carta do benzeno deve destacar a noção introdutória de estabilidade diferenciada",
    ],
    rewards: { unlockedMolecule: "benzeno", unlockedTitle: "Arquiteto do Reino do Carbono" },
    feedback: {
      excellent: "Excelente escolha. O Benzeno representa uma estrutura aromática com estabilidade especial e conclui o capítulo de forma exemplar.",
      inadequate: "Essa molécula não representa a estabilidade especial exigida pela Coroa Aromática. Reavalie a diferença entre insaturação comum e aromaticidade.",
    },
    score: defaultScore,
  },
];
